CREATE OR REPLACE TABLE `store_coupons` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `code` VARCHAR(255) NOT NULL,
    `discount` DECIMAL(10, 2) NOT NULL,
    `exp` TIMESTAMP NOT NULL,
    `status` ENUM('active', 'inactive') NOT NULL DEFAULT 'active',
    `remaining` INT NOT NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
  ) ENGINE = InnoDB DEFAULT CHARSET = utf8;
